config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new,:create,:show,:index]

  resources :games, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create, :update]
  end

  resources :tags, only: [:index, :show]

  resources :user_games, only: [:create, :destroy]

  root 'welcome#index'

  get '/login' => 'sessions#new'

  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, length: { minimum: 4 }
	belongs_to :user
	belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :user_games, class_name: "UserGame", foreign_key: :game_id
	has_many :owners, through: :user_games, source: :user
	has_many :ratings
	has_many :raters, through: :ratings, source: :user
	has_many :comments
	has_many :commenters, through: :comments, source: :user
	has_many :taggings
	has_many :tags, through: :taggings

	validates :name, presence: true


	def average_rating
		(self.ratings.map(&:score).reduce(:+).to_f)/self.ratings.count 
	end

	def duration_of_game
		Range.new(self.min_duration_of_game, self.max_duration_of_game)
	end

	def number_of_players
		Range.new(self.min_number_of_players, self.max_number_of_players)
	end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	belongs_to :game

	validates :user_id, presence: true
	validates :game_id, presence: true 	
	validates :score, presence: true
	validates_uniqueness_of :user_id, :scope => :game_id, :message=>"You can't rate a game more than once", on: 'create'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :tagged_games, through: :taggings, source: :game

	validates :name, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
	belongs_to :tag
	belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_games, class_name: "UserGame", foreign_key: :user_id
  has_many :owned_games, through: :user_games, source: :game
  has_many :ratings
  has_many :rated_games, through: :ratings, source: :game
	has_many :comments
  has_many :commented_games, through: :comments, source: :game

	validates :email, presence: true
	validates :username, presence: true
	validates :name, presence: true

	has_secure_password
end

app/models/user_game.rb
class UserGame < ActiveRecord::Base
	belongs_to :user
	belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  protect_from_forgery with: :exception
  before_filter :require_login


	private

	  def require_login
	    unless current_user
	      redirect_to root_path
	    end
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.update(user: current_user, game_id: game_params[:game_id])

    @comment.save
    redirect_to @comment.game
  end

  def destroy
    @game = Game.find(params[:game_id])
    @comment = @game.comments.find(params[:id])
    @comment.destroy
    redirect_to game_path(@game)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def game_params
    params.permit(:game_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all.select{|game| game unless game.average_rating.nan?}.sort_by(&:average_rating).reverse[0..9]
    @prefixes = ('A'..'Z').to_a
    if params[:letter]
      @games = Game.where("games.name LIKE :letter", { letter: params[:letter]}).page(params[:page])
    end
  end

  def show
    @user = current_user
    @game = Game.find_by(id: params[:id])
    @tags = @game.tags
    @comments = @game.comments.sort_by(&:created_at).reverse
    @comment = Comment.new
    @rating = Rating.find_by(user: @user, game: @game) || Rating.new

    if @user.owned_games.include?(@game)
      @owned_game = UserGame.find_by(user: current_user, game: @game)
    else
      @owned_game = UserGame.new
    end
  end



end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    rating = Rating.new(user: current_user, game_id: game_params)
    rating.update(rating_params)
    redirect_to rating.game
  end

  def update
    rating = Rating.find_by(user: current_user, game_id: game_params)
    rating.update(rating_params)
    redirect_to rating.game
  end

  private

  def rating_params
    params.require(:rating).permit(:score)
  end

  def game_params
    params.require(:game_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :require_login

	def new
		@user = User.new
	end

	def create
		@user = User.find_by(username: params[:user][:username])
		if @user && @user.authenticate(params[:user][:password])
			log_in(@user)
			redirect_to user_path(@user)
		else
			@user = User.new
			@errors = 'invalid email and/or password'
			render 'new'
		end
	end	

	def destroy
		log_out
		redirect_to login_path
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
    @mechanics = Tag.where(category: "mechanic")
    @genres = Tag.where(category: "genre")
	end

	def show
    puts params
    @tag = Tag.find_by(id: params[:id])
    @games = @tag.tagged_games
	end
end

app/controllers/user_games_controller.rb
  class UserGamesController < ApplicationController
    def create
      @game = Game.find_by(id: params[:game_id])
      current_user.owned_games << @game
      redirect_to :back
    end

    def destroy
      @game = Game.find_by(id: params[:game_id])
      current_user.owned_games.destroy(@game)
      redirect_to :back
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login, :only => [:new, :create]

	def index
		@users = User.all
	end

	def new
		@user = User.new
		render 'new'
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(@user)
		else
			@errors = @user.errors.full_messages
			render 'new'
		end 
	end

	def show
		@user = User.find_by(id: params[:id])
		@games = @user.owned_games
		@comments = @user.comments
		@ratings = @user.ratings
	end

	private
		def user_params
			params.require(:user).permit(:name, :username, :password, :email)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_filter :require_login, :only => [:index]
	def index
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p><%= comment.body %></p>
  <% if comment.user.owned_games.include?(comment.game) %>
    <p class="owner-stamp">
    <%= link_to "#{comment.user.username}", comment.user %> (owns this game)
  <% else %>
    <p class="normal-stamp">
    <%= link_to "#{comment.user.username}", comment.user %>
  <% end %>
    <%= time_ago_in_words(comment.created_at) %> ago
    </p>
</div>

<% if current_user && current_user.is_admin %>
  <%= link_to 'Destroy', [comment.game, comment], method: :delete, data: { confirm: 'Are you sure you want to delete this comment?' } %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [game, comment] do |f| %>
 
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(comment.errors.count, "error") %> prohibited
        this comment from being saved:
      </h2>
      <ul>
        <% comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.text_area :body, placeholder: "Write your comment here" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/games/_add_game_button.html.erb
<%= form_for game, url: user_games_path, method: "post" do |f| %>
  <%=hidden_field_tag 'game_id', game.id %>
  <%=f.submit "Add Game To Library"%>
<% end %>

app/views/games/_alphabetized_games.html.erb
<div class="container">
  <ul>
    <% @games.each do |game| %>
      <li><%= render partial: 'game', locals: {game: game} %>
        <% unless game.owners.include?(current_user) %>
          <%= form_for game, url: user_games_path, method: "post" do |f| %>
            <%=hidden_field_tag 'game_id', game.id %>
            <%=f.submit "Add game to library"%>
          <% end %>
        <% else %>
          <%= form_for game, url: "user_games/#{game.id}", method: 'delete' do |f| %>
            <%=hidden_field_tag 'game_id', game.id %>
            <%=f.submit "Remove owned game"%>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<%= paginate @games %>

app/views/games/_game.html.erb
<td><%= link_to "#{game.name}", game %></td>

<% if game.average_rating.nan? %>
	<td>N/A</td>
<% else %>
	<td><%= "%0.1f" % game.average_rating %></td>
<% end %>

<td><%= game.comments.count %></td>

<td>
	<% if game.owners.include?(current_user) %>
	  <%= form_for game, url: "user_games/#{game.id}", method: 'delete' do |f| %>
	    <%=hidden_field_tag 'game_id', game.id %>
	    <%=f.submit "Remove Game From Library"%>
	  <% end %>
	<% else %>
	  <%= form_for game, url: user_games_path, method: "post" do |f| %>
	    <%=hidden_field_tag 'game_id', game.id %>
	    <%=f.submit "Add Game To Library"%>
	  <% end %>
	<% end %>
</td>

app/views/games/_remove_game_button.html.erb
<%= form_for game, url: "user_games/#{game.id}", method: 'delete' do |f| %>
  <%=hidden_field_tag 'game_id', game.id %>
  <%=f.submit "Remove Game From Library"%>
<% end %>

app/views/games/_show.html.erb
<%= link_to "#{game.name}", game_path(game) %>
<%= game.average_rating %>
<br>
<% comment = game.comments.sample %>
<% if comment %>
  Someone Commented: <%= comment.body %>
<% end %>

app/views/games/index.html.erb
<div class="container">

  <div class="letter-prefixes">
    <h1>Find Game By Letter:</h1>
    <% @prefixes.each do |letter| %>
      <%= link_to letter, games_path(letter: "#{letter}%"), class: 'letter-link' %>
    <% end %> 
  </div>

  <div class="tags">
    <h4>Or, browse by <%= link_to "Genre/Mechanic", tags_path %></h4>
  </div>

  <div class="games">
    <% if params[:letter] %>
      <h2>Games beginning with <%= params[:letter][0] %>:</h2>
    <% else %>
      <h2>Top Rated Games:</h2>
    <% end %>
    <table>
      <tr>
        <th>Name</th>
        <th>Rating</th>
        <th>Comments</th>
        <th></th>
      </tr>
      <% @games.each do |game| %>
        <tr><%= render partial: 'game', locals: {game: game} %>
        </tr>
      <% end %>
    </table>
  </div>

  <% if params[:letter] %>
    <div class="pagination"> 
      <%= link_to "Top Ten Games", games_path, class: "nav-link" %>
      <%= paginate @games %>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="game-info">
    <h1><%= @game.name %></h1>
    <div class="info-card">
      <table>
        <tr>
          <td>Avg. Rating:</td>
        <% if @game.ratings.any? %>
          <td><%= "%0.1f" % @game.average_rating %>/5 (<%= @game.ratings.count %> votes)</td>
        <% else %>
          <td>Not yet rated</td>
        <% end %>
        </tr>
        <tr>
          <td>Num. Players:</td>
          <td><%= @game.min_number_of_players %> - <%= @game.max_number_of_players %></td>
        </tr>
        <tr>
          <td>Duration:</td>
          <td><%= @game.min_duration_of_game %> - <%= @game.max_duration_of_game %> minutes</td>
        </tr>
        <tr>
        <td>Genres:</td>
          <td>
            <% @tags.each do |tag| %>
              <%= link_to "#{tag.name}", tag_path(tag) if tag.category == "genre" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Mechanics:</td>
          <td>
            <% @tags.each do |tag| %>
              <%= link_to "#{tag.name}", tag_path(tag) if tag.category == "mechanic" %>
            <% end %>
          </td>
        </tr> 
      </table>
    </div>
    <div class="description">
      <h3>Description:</h3>
      <p><%= @game.description %></p>
    </div>
  </div>

  <div class="rate-game">
    <%= render partial: 'ratings/form', locals: { user: @user, game: @game, rating: @rating } %>
  </div>

  <div class="add-or-remove-button">
    <% if @owned_game.user == nil %>
      <%= render partial: 'add_game_button', locals: {game: @game} %>
    <% else %>
      <%= form_for @owned_game, url: user_game_path, method: 'delete' do |f| %>
        <%=hidden_field_tag 'game_id', @game.id %>
        <%=f.submit "Remove Game From Library"%>
      <% end %>
    <% end %>
  </div>

  <div class="comments">

    <h3>Join the discussion!</h3>

    <div class="comment-form">
      <%= render partial: 'comments/form', locals: {user: current_user, game: @game, comment: @comment} %>
    </div>

    <% @comments.each do |comment| %>
      <%= render partial: 'comments/comment', locals: {comment: comment} %>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <h1 class="brand"><a class="navbar-brand" href="/">SmorgasBoard</a></h1>
  <nav>
    <% if current_user %>
      <%= render "layouts/nav_loggedin" %>
    <% else %>
      <%= render "layouts/nav_loggedout" %>
    <% end %>
  </nav>
</header>

app/views/layouts/_nav_loggedin.html.erb
<ul>
  <li><%= link_to "My Profile", current_user %></li>
  <li><%= link_to "All Games", games_path %></li>
  <li><%= link_to "Sign Out", logout_path, method: :delete %></a></li>
</ul>

app/views/layouts/_nav_loggedout.html.erb
<ul>
  <li><%= link_to "Register", new_user_path %></li>
  <li><%= link_to "Log In", login_path %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>SmorgasBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/ratings/_form.html.erb
<%= form_for [game, rating] do |f| %> 
  <p>
    <% if rating.score %>
      <p>You gave it a rating of <%= rating.score %> out of 5.</p>
    <% end %>
    <%= f.label :score, "Rating:" %>

    <%= f.radio_button :score, 1 %>
    <%= f.radio_button :score, 2 %>
    <%= f.radio_button :score, 3 %>
    <%= f.radio_button :score, 4 %>
    <%= f.radio_button :score, 5 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/tags/index.html.erb
<div class="container">
  <div class="genres">
    <h1>Genres</h1>
    <% @genres.each do |genre| %>
      <li><%= link_to "#{genre.name}", genre %></li>
    <% end %>
  </div>  

  <div class="mechanics">
    <h1>Mechanics</h1>
    <% @mechanics.each do |mech| %>
      <li><%= link_to "#{mech.name}", mech %></li>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container">
  <h1><%= @tag.name %></h1>
  <h3><%= @tag.description %></h3>

  <% @games.each do |game| %>
    <li><%= link_to "#{game.name}", game %></li>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
	<table>
		<tr>
			<td><%= f.label :name %></td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td><%= f.label :username %></td>
			<td><%= f.text_field :username %></td>
		</tr>
		<tr>
			<td><%= f.label :email %></td>
			<td><%= f.email_field :email %></td>
		</tr>
		<tr>
			<td><%= f.label :password %></td>
			<td><%= f.password_field :password %></td>
		</tr>
		<tr>
			<td></td>
			<td><%= f.submit %></td>
		</tr>
	</table>
<% end %>

app/views/users/new.html.erb
<div class="container">
	<% if @errors %>
		<% @errors.each do |error| %>
			<p><%= error %></p>
		<% end %>
	<% end %>
	
	<%= render partial: 'form', locals: {user: @user} %>
	
</div>

app/views/users/show.html.erb
<div class="container">
  <% if current_user == @user %>
    <h1>Welcome, <%= @user.username %>!</h1>
  <% else %>
    <h1>Welcome to <%= @user.username %>'s profile</h1>
  <% end %>

  <div class="games">
    <h3><%= @user.name %> owns these games:</h3>

    <% if @games.empty? %>
      <% if current_user == @user %>
        <p>It looks like you haven't added any game to your library :(</p>
        <%= button_to "Browse and add games to your library!", games_path, method: 'get' if current_user == @user %>
      <% else %>
        <p><%= @user.username %> hasn't added any games to his/her library yet :(</p>
      <% end %>
    <% end %>

    <% @games.each do |game| %>
      <li>
        <%= link_to "#{game.name}", game %>
        <%= form_for game, url: user_game_path, method: 'delete' do |f| %>
          <%=hidden_field_tag 'game_id', game.id %>
          <%=f.submit "Remove Game From Library"%>
        <% end %>
      </li>
    <% end %>

  </div>

  <div class="user-comments">
    <h3><%= @user.name %>'s Comments:</h3>
    <% if @comments.empty? %>
      <p>No comments yet!</p>
    <% else %>
      <% @comments.each do |comment| %>
        <li>
          <%= link_to "#{comment.game.name}", comment.game %>
          <p><%= comment.body %></p>
        </li>
      <% end %>
    <% end %>
  </div>

  <div class="user-ratings">
    <h3><%= @user.name %>'s' game ratings:</h3>
    <% if @ratings.empty? %>
      <p>No ratings yet!</p>
    <% else %>
      <% @ratings.each do |rating| %>
        <li>
          <%= link_to "#{rating.game.name}", rating.game %> - <%= rating.score %> out of 5
          <br><br>
        </li>
      <% end %>
    <% end %>
  </div>

</div>

app/views/welcome/index.html.erb
<div class="container">
	<h1>Welcome to Social Gaming!</h1>
</div>